use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Token {
    // Littéraux
    Entier(i64),
    Décimal(String),
    Texte(String),
    Booléen(bool),
    Nul,

    // Identifiants
    Identifiant(String),

    // Mots-clés - Contrôle de flux
    Si,
    Alors,
    Sinon,
    SinonSi,
    Fin,
    TantQue,
    Pour,
    Dans,
    De,
    À,
    Pas,
    Faire,
    Interrompre,
    Continuer,
    Cas,
    ParDéfaut,
    Sélectionner,

    // Mots-clés - Fonctions
    Fonction,
    Retourne,
    Récursif,
    Asynchrone,
    Attends,

    // Mots-clés - Types primitifs
    EntierType,
    DécimalType,
    TexteType,
    BooléenType,
    NulType,
    RienType,

    // Mots-clés - Types collections
    TableauType,
    ListeType,
    PileType,
    FileType,
    ListeChaînéeType,
    DictionnaireType,
    EnsembleType,
    TupleType,

    // Mots-clés - POO
    Classe,
    Hérite,
    Publique,
    Privé,
    Protégé,
    Constructeur,
    Ceci,
    Base,
    Interface,
    Implémente,
    Abstraite,
    Virtuelle,
    Surcharge,
    Nouveau,

    // Mots-clés - Modules
    Module,
    Importe,
    Exporte,
    Depuis,

    // Mots-clés - FFI
    Externe,
    PointeurType,
    PointeurVideType,
    CIntType,
    CLongType,
    CDoubleType,
    CCharType,

    // Mots-clés - Divers
    Soit,
    Constante,
    Mutable,
    Comme,
    Est,
    Vrai,
    Faux,
    Où,
    Et,
    Ou,
    Non,

    // Opérateurs arithmétiques
    Plus,
    Moins,
    Étoile,
    Slash,
    Pourcentage,
    DoubleÉtoile,
    DoubleSlash,

    // Opérateurs de comparaison
    Égal,
    Différent,
    Inférieur,
    Supérieur,
    InférieurÉgal,
    SupérieurÉgal,

    // Opérateurs logiques
    DoubleEt,
    DoubleOu,
    PointExclamation,

    // Opérateurs d'affectation
    Affecte,
    PlusAffecte,
    MoinsAffecte,
    ÉtoileAffecte,
    SlashAffecte,
    PourcentageAffecte,

    // Opérateurs divers
    Flèche,
    DoubleFlèche,
    Pipe,
    DoublePoint,
    Point,
    Virgule,
    PointVirgule,
    DeuxPoints,
    PointInterrogation,
    EtCommercial,
    Tiret,
    Arobase,
    Dièse,

    // Délimiteurs
    ParenthèseOuvrante,
    ParenthèseFermante,
    CrochetOuvrant,
    CrochetFermant,
    AccoladeOuvrante,
    AccoladeFermante,

    // Spécial
    FinDeFichier,
    NouvelleLigne,
    Indentation,
    Désindentation,
}

#[derive(Debug, Clone)]
pub struct TokenAvecPosition {
    pub token: Token,
    pub position: crate::error::Position,
}

impl TokenAvecPosition {
    pub fn nouveau(token: Token, position: crate::error::Position) -> Self {
        Self { token, position }
    }
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Token::Entier(v) => write!(f, "{}", v),
            Token::Décimal(v) => write!(f, "{}", v),
            Token::Texte(v) => write!(f, "\"{}\"", v),
            Token::Booléen(v) => write!(f, "{}", if *v { "vrai" } else { "faux" }),
            Token::Nul => write!(f, "nul"),
            Token::Identifiant(v) => write!(f, "{}", v),
            Token::Si => write!(f, "si"),
            Token::Alors => write!(f, "alors"),
            Token::Sinon => write!(f, "sinon"),
            Token::SinonSi => write!(f, "sinonsi"),
            Token::Fin => write!(f, "fin"),
            Token::TantQue => write!(f, "tantque"),
            Token::Pour => write!(f, "pour"),
            Token::Dans => write!(f, "dans"),
            Token::De => write!(f, "de"),
            Token::À => write!(f, "à"),
            Token::Pas => write!(f, "pas"),
            Token::Faire => write!(f, "faire"),
            Token::Interrompre => write!(f, "interrompre"),
            Token::Continuer => write!(f, "continuer"),
            Token::Cas => write!(f, "cas"),
            Token::ParDéfaut => write!(f, "pardéfaut"),
            Token::Sélectionner => write!(f, "sélectionner"),
            Token::Fonction => write!(f, "fonction"),
            Token::Retourne => write!(f, "retourne"),
            Token::Récursif => write!(f, "récursif"),
            Token::Asynchrone => write!(f, "asynchrone"),
            Token::Attends => write!(f, "attends"),
            Token::EntierType => write!(f, "entier"),
            Token::DécimalType => write!(f, "décimal"),
            Token::TexteType => write!(f, "texte"),
            Token::BooléenType => write!(f, "booléen"),
            Token::NulType => write!(f, "nul"),
            Token::RienType => write!(f, "rien"),
            Token::TableauType => write!(f, "tableau"),
            Token::ListeType => write!(f, "liste"),
            Token::PileType => write!(f, "pile"),
            Token::FileType => write!(f, "file"),
            Token::ListeChaînéeType => write!(f, "liste_chaînée"),
            Token::DictionnaireType => write!(f, "dictionnaire"),
            Token::EnsembleType => write!(f, "ensemble"),
            Token::TupleType => write!(f, "tuple"),
            Token::Classe => write!(f, "classe"),
            Token::Hérite => write!(f, "hérite"),
            Token::Publique => write!(f, "publique"),
            Token::Privé => write!(f, "privé"),
            Token::Protégé => write!(f, "protégé"),
            Token::Constructeur => write!(f, "constructeur"),
            Token::Ceci => write!(f, "ceci"),
            Token::Base => write!(f, "base"),
            Token::Interface => write!(f, "interface"),
            Token::Implémente => write!(f, "implémente"),
            Token::Abstraite => write!(f, "abstraite"),
            Token::Virtuelle => write!(f, "virtuelle"),
            Token::Surcharge => write!(f, "surcharge"),
            Token::Nouveau => write!(f, "nouveau"),
            Token::Module => write!(f, "module"),
            Token::Importe => write!(f, "importe"),
            Token::Exporte => write!(f, "exporte"),
            Token::Depuis => write!(f, "depuis"),
            Token::Externe => write!(f, "externe"),
            Token::PointeurType => write!(f, "pointeur"),
            Token::PointeurVideType => write!(f, "pointeur_vide"),
            Token::CIntType => write!(f, "c_int"),
            Token::CLongType => write!(f, "c_long"),
            Token::CDoubleType => write!(f, "c_double"),
            Token::CCharType => write!(f, "c_char"),
            Token::Soit => write!(f, "soit"),
            Token::Constante => write!(f, "constante"),
            Token::Mutable => write!(f, "mutable"),
            Token::Comme => write!(f, "comme"),
            Token::Est => write!(f, "est"),
            Token::Vrai => write!(f, "vrai"),
            Token::Faux => write!(f, "faux"),
            Token::Où => write!(f, "où"),
            Token::Et => write!(f, "et"),
            Token::Ou => write!(f, "ou"),
            Token::Non => write!(f, "non"),
            Token::Plus => write!(f, "+"),
            Token::Moins => write!(f, "-"),
            Token::Étoile => write!(f, "*"),
            Token::Slash => write!(f, "/"),
            Token::Pourcentage => write!(f, "%"),
            Token::DoubleÉtoile => write!(f, "**"),
            Token::DoubleSlash => write!(f, "//"),
            Token::Égal => write!(f, "=="),
            Token::Différent => write!(f, "!="),
            Token::Inférieur => write!(f, "<"),
            Token::Supérieur => write!(f, ">"),
            Token::InférieurÉgal => write!(f, "<="),
            Token::SupérieurÉgal => write!(f, ">="),
            Token::DoubleEt => write!(f, "&&"),
            Token::DoubleOu => write!(f, "||"),
            Token::PointExclamation => write!(f, "!"),
            Token::Affecte => write!(f, "="),
            Token::PlusAffecte => write!(f, "+="),
            Token::MoinsAffecte => write!(f, "-="),
            Token::ÉtoileAffecte => write!(f, "*="),
            Token::SlashAffecte => write!(f, "/="),
            Token::PourcentageAffecte => write!(f, "%="),
            Token::Flèche => write!(f, "->"),
            Token::DoubleFlèche => write!(f, "=>"),
            Token::Pipe => write!(f, "|>"),
            Token::DoublePoint => write!(f, ".."),
            Token::Point => write!(f, "."),
            Token::Virgule => write!(f, ","),
            Token::PointVirgule => write!(f, ";"),
            Token::DeuxPoints => write!(f, ":"),
            Token::PointInterrogation => write!(f, "?"),
            Token::EtCommercial => write!(f, "&"),
            Token::Tiret => write!(f, "_"),
            Token::Arobase => write!(f, "@"),
            Token::Dièse => write!(f, "#"),
            Token::ParenthèseOuvrante => write!(f, "("),
            Token::ParenthèseFermante => write!(f, ")"),
            Token::CrochetOuvrant => write!(f, "["),
            Token::CrochetFermant => write!(f, "]"),
            Token::AccoladeOuvrante => write!(f, "{{"),
            Token::AccoladeFermante => write!(f, "}}"),
            Token::FinDeFichier => write!(f, "<EOF>"),
            Token::NouvelleLigne => write!(f, "<NL>"),
            Token::Indentation => write!(f, "<IND>"),
            Token::Désindentation => write!(f, "<DIND>"),
        }
    }
}
